// voxline/Output/PasteboardWriter.swift
import AppKit

/// The only writer of voxline's pasteboard hint types.
@MainActor
enum PasteboardWriter {

    /// De-facto pasteboard hint types (nspasteboard.org) that well-behaved
    /// clipboard managers (Maccy, Paste, Pastebot, Alfred) honor by NOT
    /// archiving the entry into history. AutoGenerated says "this is a
    /// programmatic write, not user-copied"; Concealed says "this contains
    /// sensitive data" — relevant because the cleaned text may carry
    /// dictated passwords, 2FA codes, etc.
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    /// clearContents, string + both hints as empty data. Returns the new changeCount.
    @discardableResult
    static func writeHinted(_ text: String, to pasteboard: NSPasteboard = .general) -> Int {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        pasteboard.setData(Data(), forType: autoGeneratedType)
        pasteboard.setData(Data(), forType: concealedType)
        return pasteboard.changeCount
    }

    /// One NSPasteboardItem whose `.string` is promised through `provider`,
    /// hints as empty data. Returns the new changeCount.
    @discardableResult
    static func writePromised(provider: NSPasteboardItemDataProvider, to pasteboard: NSPasteboard) -> Int {
        let item = NSPasteboardItem()
        item.setDataProvider(provider, forTypes: [.string])
        item.setData(Data(), forType: autoGeneratedType)
        item.setData(Data(), forType: concealedType)
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }
}
