// voxlineTests/PasteboardWriterTests.swift
import AppKit
import Testing
@testable import voxline

@MainActor
@Suite struct PasteboardWriterTests {

    final class StubProvider: NSObject, NSPasteboardItemDataProvider {
        let text: String
        private(set) var calls: [NSPasteboard.PasteboardType] = []

        init(text: String) { self.text = text }

        func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {
            calls.append(type)
            item.setString(text, forType: type)
        }
    }

    private func makeBoard() -> NSPasteboard {
        NSPasteboard(name: NSPasteboard.Name("voxline-test-\(UUID())"))
    }

    @Test func hint_types_use_nspasteboard_org_names() {
        #expect(PasteboardWriter.autoGeneratedType.rawValue == "org.nspasteboard.AutoGeneratedType")
        #expect(PasteboardWriter.concealedType.rawValue == "org.nspasteboard.ConcealedType")
        #expect(ClipboardInjector.autoGeneratedType == PasteboardWriter.autoGeneratedType)
        #expect(ClipboardInjector.concealedType == PasteboardWriter.concealedType)
    }

    @Test func write_hinted_sets_string_and_empty_hints() {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        board.clearContents()
        board.setString("OLD", forType: .string)
        board.setString("<i>old</i>", forType: .html)

        let changeCount = PasteboardWriter.writeHinted("hello", to: board)

        #expect(changeCount == board.changeCount)
        #expect(board.string(forType: .string) == "hello")
        #expect(board.data(forType: PasteboardWriter.autoGeneratedType) == Data())
        #expect(board.data(forType: PasteboardWriter.concealedType) == Data())
        #expect(board.data(forType: .html) == nil)
        #expect(board.pasteboardItems?.count == 1)
    }

    @Test func write_hinted_bumps_change_count() {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        board.clearContents()
        let before = board.changeCount

        let changeCount = PasteboardWriter.writeHinted("x", to: board)

        #expect(changeCount > before)
    }

    @Test func write_promised_serves_string_through_provider_once() throws {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        board.clearContents()
        board.setString("OLD", forType: .string)
        let provider = StubProvider(text: "P")

        let changeCount = PasteboardWriter.writePromised(provider: provider, to: board)

        #expect(changeCount == board.changeCount)
        #expect(provider.calls.isEmpty)
        #expect(board.string(forType: .string) == "P")
        #expect(provider.calls == [.string])
        #expect(board.data(forType: PasteboardWriter.autoGeneratedType) == Data())
        #expect(board.data(forType: PasteboardWriter.concealedType) == Data())
        let items = try #require(board.pasteboardItems)
        #expect(items.count == 1)
        #expect(provider.calls == [.string])
    }
}
