// voxlineTests/PasteInjectorTests.swift
import AppKit
import ApplicationServices
import Testing
@testable import voxline

@MainActor
@Suite(.timeLimit(.minutes(1))) struct PasteInjectorTests {

    struct ThrowingSnapshotter: PasteboardSnapshotting {
        let reason: String
        func capture(from pasteboard: NSPasteboard) throws -> PasteboardSnapshot {
            throw PasteboardSnapshot.SnapshotError.refuseToClobber(reason: reason)
        }
    }

    struct Harness {
        let board: NSPasteboard
        let clock: ManualClock
        let posts: LockedBox<Int>
        let injector: PasteInjector
    }

    private func makeHarness(
        snapshotter: PasteboardSnapshotting = DefaultPasteboardSnapshotter()
    ) -> Harness {
        let board = NSPasteboard(name: NSPasteboard.Name("voxline-test-\(UUID())"))
        board.clearContents()
        board.setString("ORIGINAL", forType: .string)
        let clock = ManualClock()
        let posts = LockedBox(0)
        var gate = ModifierReleaseGate()
        gate.flagsState = { [] }
        gate.forceClear = {}
        let injector = PasteInjector(
            pasteboard: board,
            snapshotter: snapshotter,
            postPaste: { posts.mutate { $0 += 1 } },
            gate: gate,
            sleep: { @MainActor in try await clock.sleep($0) }
        )
        return Harness(board: board, clock: clock, posts: posts, injector: injector)
    }

    private func eventually(_ condition: () -> Bool) async -> Bool {
        let deadline = ContinuousClock.now + .seconds(2)
        while !condition() {
            if ContinuousClock.now >= deadline { return false }
            try? await Task.sleep(for: .milliseconds(1))
        }
        return true
    }

    private func isOurs(_ board: NSPasteboard) -> Bool {
        board.data(forType: PasteboardWriter.autoGeneratedType) != nil
    }

    /// Starts a paste and drives the clock through the 50 ms settle delay
    /// until Cmd+V is posted and both the verify poll and the restore
    /// ceiling are waiting.
    private func startPaste(
        _ h: Harness,
        element: (any AXTextElement)? = nil,
        focused: @escaping @Sendable () -> AXElementRef? = { nil },
        beforeArming: () -> Void = {}
    ) async -> Task<PasteInjector.Outcome, Never> {
        let postsBefore = h.posts.read()
        let pendingBefore = h.clock.pendingCount
        let task = Task { await h.injector.paste("PASTED", element: element, trigger: [], focused: focused) }
        #expect(await eventually { h.clock.pendingCount == pendingBefore + 1 })
        beforeArming()
        await h.clock.advance(by: .milliseconds(50))
        #expect(await eventually { h.posts.read() == postsBefore + 1 })
        #expect(await eventually { h.clock.pendingCount == pendingBefore + 2 })
        return task
    }

    private func finish(_ h: Harness, _ task: Task<PasteInjector.Outcome, Never>) async {
        await h.clock.advance(by: .seconds(2))
        _ = await task.value
        await h.injector.pendingRestore?.value
    }

    @Test func restores_150ms_after_the_provider_is_read() async {
        let h = makeHarness()
        defer { h.board.releaseGlobally() }
        let task = await startPaste(h)
        #expect(await eventually { h.clock.pendingCount == 2 })

        #expect(h.board.string(forType: .string) == "PASTED")
        #expect(await eventually { h.clock.pendingCount == 3 })

        await h.clock.advance(by: .milliseconds(149))
        #expect(isOurs(h.board))
        #expect(h.board.string(forType: .string) == "PASTED")

        await h.clock.advance(by: .milliseconds(1))
        #expect(await eventually { h.board.string(forType: .string) == "ORIGINAL" })
        #expect(!isOurs(h.board))

        await finish(h, task)
    }

    @Test func early_provider_call_is_ignored() async {
        let h = makeHarness()
        defer { h.board.releaseGlobally() }
        let task = await startPaste(h, beforeArming: {
            #expect(h.board.string(forType: .string) == "PASTED")
        })
        #expect(await eventually { h.clock.pendingCount == 2 })
        #expect(h.board.string(forType: .string) == "PASTED")

        await h.clock.advance(by: .milliseconds(1_499))
        #expect(isOurs(h.board))

        await h.clock.advance(by: .milliseconds(1))
        #expect(await eventually { h.board.string(forType: .string) == "ORIGINAL" })
        #expect(!isOurs(h.board))

        await finish(h, task)
    }

    @Test func early_provider_call_then_a_user_copy_skips_the_ceiling_restore() async {
        let h = makeHarness()
        defer { h.board.releaseGlobally() }
        let task = await startPaste(h, beforeArming: {
            #expect(h.board.string(forType: .string) == "PASTED")
        })
        #expect(await eventually { h.clock.pendingCount == 2 })
        h.board.clearContents()
        h.board.setString("USER", forType: .string)

        await h.clock.advance(by: .milliseconds(1_500))
        await h.injector.pendingRestore?.value

        #expect(h.board.string(forType: .string) == "USER")
        await finish(h, task)
    }

    @Test func ceiling_restores_without_a_provider_call() async {
        let h = makeHarness()
        defer { h.board.releaseGlobally() }
        let task = await startPaste(h)
        #expect(await eventually { h.clock.pendingCount == 2 })

        await h.clock.advance(by: .milliseconds(1_499))
        #expect(isOurs(h.board))

        await h.clock.advance(by: .milliseconds(1))
        #expect(await eventually { !isOurs(h.board) })
        #expect(h.board.string(forType: .string) == "ORIGINAL")

        await finish(h, task)
    }

    @Test func moved_change_count_skips_restore() async {
        let h = makeHarness()
        defer { h.board.releaseGlobally() }
        let task = await startPaste(h)
        #expect(await eventually { h.clock.pendingCount == 2 })
        h.board.clearContents()
        h.board.setString("USER", forType: .string)

        await h.clock.advance(by: .milliseconds(1_600))
        await h.injector.pendingRestore?.value

        #expect(h.board.string(forType: .string) == "USER")
        await finish(h, task)
    }

    @Test func next_paste_waits_for_the_tail() async {
        let h = makeHarness()
        defer { h.board.releaseGlobally() }
        let first = await startPaste(h)
        #expect(await eventually { h.clock.pendingCount == 2 })
        let second = Task { await h.injector.paste("SECOND", element: nil, trigger: [], focused: { nil }) }

        await h.clock.advance(by: .milliseconds(1_499))
        #expect(await first.value == .pasted(verified: false))
        #expect(h.posts.read() == 1)
        #expect(h.clock.pendingCount == 1)

        await h.clock.advance(by: .milliseconds(1))
        #expect(await eventually { h.clock.pendingCount == 1 && isOurs(h.board) })
        #expect(h.posts.read() == 1)

        await h.clock.advance(by: .milliseconds(50))
        #expect(await eventually { h.posts.read() == 2 })

        await h.clock.advance(by: .seconds(2))
        #expect(await second.value == .pasted(verified: false))
        await h.injector.pendingRestore?.value
        #expect(h.board.string(forType: .string) == "ORIGINAL")
    }

    @Test func verified_when_value_changes() async {
        let h = makeHarness()
        defer { h.board.releaseGlobally() }
        let fake = FakeAXTextElement()
        fake.strings[kAXValueAttribute] = [.value("a"), .value("ab")]
        let task = await startPaste(h, element: fake)

        await h.clock.advance(by: .milliseconds(300))

        #expect(await task.value == .pasted(verified: true))
        #expect(fake.reads.filter { $0 == kAXValueAttribute }.count == 2)
        await finish(h, task)
    }

    @Test func unverified_when_value_unchanged_for_300ms() async {
        let h = makeHarness()
        defer { h.board.releaseGlobally() }
        let fake = FakeAXTextElement()
        fake.setValue("a")
        let task = await startPaste(h, element: fake)

        await h.clock.advance(by: .milliseconds(300))

        #expect(await task.value == .pasted(verified: false))
        #expect(fake.reads.filter { $0 == kAXValueAttribute }.count == 7)
        await finish(h, task)
    }

    @Test func focus_moved_on_the_first_poll() async {
        let h = makeHarness()
        defer { h.board.releaseGlobally() }
        let first = FakeAXTextElement().ref
        let other = FakeAXTextElement(pid: 9191).ref
        let calls = LockedBox(0)
        let focused: @Sendable () -> AXElementRef? = {
            calls.mutate { $0 += 1 }
            return calls.read() == 1 ? first : other
        }
        let task = await startPaste(h, focused: focused)

        await h.clock.advance(by: .milliseconds(300))

        #expect(await task.value == .focusMoved)
        #expect(calls.read() == 2)
        await finish(h, task)
    }

    @Test func element_ref_is_the_focus_baseline() async {
        let h = makeHarness()
        defer { h.board.releaseGlobally() }
        let fake = FakeAXTextElement()
        fake.setValue("a")
        let other = FakeAXTextElement(pid: 9191).ref
        let calls = LockedBox(0)
        let focused: @Sendable () -> AXElementRef? = {
            calls.mutate { $0 += 1 }
            return other
        }
        let task = await startPaste(h, element: fake, focused: focused)

        await h.clock.advance(by: .milliseconds(300))

        #expect(await task.value == .focusMoved)
        #expect(calls.read() == 1)
        await finish(h, task)
    }

    @Test func overlapping_pastes_keep_the_users_clipboard() async {
        let h = makeHarness()
        defer { h.board.releaseGlobally() }
        let first = Task { await h.injector.paste("FIRST", element: nil, trigger: [], focused: { nil }) }
        let second = Task { await h.injector.paste("SECOND", element: nil, trigger: [], focused: { nil }) }
        #expect(await eventually { h.clock.pendingCount == 1 })

        await h.clock.advance(by: .milliseconds(50))
        #expect(await eventually { h.posts.read() == 1 })
        #expect(await eventually { h.clock.pendingCount == 2 })
        #expect(isOurs(h.board))

        await h.clock.advance(by: .milliseconds(1_499))
        #expect(await first.value == .pasted(verified: false))
        #expect(h.posts.read() == 1)

        await h.clock.advance(by: .milliseconds(1))
        #expect(await eventually { h.clock.pendingCount == 1 && isOurs(h.board) })
        await h.clock.advance(by: .milliseconds(50))
        #expect(await eventually { h.posts.read() == 2 })
        #expect(h.board.string(forType: .string) == "SECOND")

        await h.clock.advance(by: .seconds(2))
        #expect(await second.value == .pasted(verified: false))
        await h.injector.pendingRestore?.value
        #expect(h.board.string(forType: .string) == "ORIGINAL")
        #expect(!isOurs(h.board))
    }

    @Test func snapshot_refusal_does_not_touch_the_board() async {
        let h = makeHarness(snapshotter: ThrowingSnapshotter(reason: "test refusal"))
        defer { h.board.releaseGlobally() }
        let changeCount = h.board.changeCount

        let outcome = await h.injector.paste("PASTED", element: nil, trigger: [], focused: { nil })

        #expect(outcome == .snapshotRefused("test refusal"))
        #expect(h.posts.read() == 0)
        #expect(h.board.changeCount == changeCount)
        #expect(h.board.string(forType: .string) == "ORIGINAL")
        await h.injector.pendingRestore?.value
        #expect(h.clock.pendingCount == 0)
        #expect(h.board.changeCount == changeCount)
    }

    @Test func hint_types_present_during_paste() async {
        let h = makeHarness()
        defer { h.board.releaseGlobally() }
        let task = await startPaste(h)

        let types = h.board.types ?? []
        #expect(types.contains(.string))
        #expect(types.contains(PasteboardWriter.autoGeneratedType))
        #expect(types.contains(PasteboardWriter.concealedType))
        #expect(h.board.data(forType: PasteboardWriter.autoGeneratedType) == Data())
        #expect(h.board.data(forType: PasteboardWriter.concealedType) == Data())
        #expect(h.board.pasteboardItems?.count == 1)

        await finish(h, task)
        #expect(h.board.data(forType: PasteboardWriter.autoGeneratedType) == nil)
        #expect(h.board.data(forType: PasteboardWriter.concealedType) == nil)
    }
}
