import AppKit
import Foundation

/// Coordinates the hotkey → audio capture → transcription → LLM cleanup →
/// clipboard inject pipeline. Updates AppState along the way.
@MainActor
final class CapturePipeline {

    private let state: AppState
    private let capture: AudioCapturing
    private let transcriber: Transcribing
    private let llm: LLMServing
    var modes: ModeRouter
    private let frontmost: FrontmostAppProviding
    private let fieldInspector: FocusedFieldInspecting
    private let injector: ClipboardInjecting
    private let historyStore: DictationHistoryStore
    private let contextCapture: ContextCapturing
    private var contextTask: Task<CapturedContext, Never>?
    private let selectionSnapshot: SelectionSnapshotting
    private var selectionTask: Task<String?, Never>?
    private var reviewExpiryTask: Task<Void, Never>?
    private let reviewLingerDuration: TimeInterval
    private let now: @Sendable () -> Date

    /// Invoked with the raw transcript when LLM cleanup fails, so the user's
    /// words survive a provider outage instead of being discarded. The default
    /// copies to the general pasteboard with the same nspasteboard.org hint
    /// types the injector uses (don't archive in clipboard managers; dictated
    /// speech can be sensitive). Settable so tests observe without touching
    /// NSPasteboard.general.
    var transcriptFallback: (String) -> Void = { transcript in
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(transcript, forType: .string)
        pasteboard.setData(Data(), forType: ClipboardInjector.autoGeneratedType)
        pasteboard.setData(Data(), forType: ClipboardInjector.concealedType)
    }

    init(
        state: AppState,
        capture: AudioCapturing,
        transcriber: Transcribing,
        llm: LLMServing,
        modes: ModeRouter,
        frontmost: FrontmostAppProviding,
        fieldInspector: FocusedFieldInspecting,
        injector: ClipboardInjecting,
        historyStore: DictationHistoryStore,
        contextCapture: ContextCapturing,
        selectionSnapshot: SelectionSnapshotting = DefaultSelectionSnapshot(),
        reviewLingerDuration: TimeInterval = 7,
        now: @escaping @Sendable () -> Date = { Date() }
    ) {
        self.state = state
        self.capture = capture
        self.transcriber = transcriber
        self.llm = llm
        self.modes = modes
        self.frontmost = frontmost
        self.fieldInspector = fieldInspector
        self.injector = injector
        self.historyStore = historyStore
        self.contextCapture = contextCapture
        self.selectionSnapshot = selectionSnapshot
        self.reviewLingerDuration = reviewLingerDuration
        self.now = now

        capture.onLevel = { [weak self] level in
            Task { @MainActor in
                guard let self else { return }
                self.state.audioLevel = level
                if level > self.state.lastPeakLevel {
                    self.state.lastPeakLevel = level
                }
            }
        }
    }

    /// Begin a new recording. Caller must ensure we're not already recording.
    func startRecording() {
        // Reject re-entry while a recording or its post-recording pipeline
        // (transcribe → LLM → paste) is still in flight. `.thinking` covers
        // the entire await chain in finalizeRecording — `state.status` is set
        // to `.thinking` synchronously before any await, so a second call
        // landing on MainActor sees it.
        //
        // Permissions errors are sticky: clearing them on a chord-press
        // would mask a real "tap is uninstalled" condition. Pipeline and
        // modelPrep errors are clearable by the user retrying.
        switch state.status {
        case .recording, .thinking, .downloadingModel, .preparingModel, .permissionsError:
            // A prewarmed engine must not be left running when recording is
            // refused — stopPrewarm is a no-op unless the engine is idling warm.
            capture.stopPrewarm()
            return
        case .idle, .error:
            break
        }
        // A new dictation supersedes any pending refinement offer.
        clearReviewSession()
        do {
            try capture.start()
        } catch {
            // A failed start must not strand a prewarmed engine — stopPrewarm
            // is a no-op unless the engine is idling warm. On the warm path,
            // AudioCaptureService.start() can throw AFTER the
            // engine-is-running check (noInputDevice / targetFormatUnavailable
            // / cannotConvertFormat), leaving the engine running with nothing
            // left to stop it.
            capture.stopPrewarm()
            setError("Audio capture failed: \(error.localizedDescription)")
            return
        }
        state.recordingStartedAt = Date()
        state.audioLevel = 0
        state.lastPeakLevel = 0
        // Scrub the prior dictation's text so it doesn't linger in process
        // memory for the lifetime of the app. Spoken content can include
        // passwords / 2FA codes / private notes; defensible-by-default hygiene.
        state.lastTranscript = nil
        state.lastCleanedText = nil
        state.lastTranscribeDuration = nil
        state.lastCleanupDuration = nil
        state.status = .recording
        let captor = contextCapture
        contextTask = Task.detached(priority: .userInitiated) {
            await captor.capture()
        }
        let snapshotter = selectionSnapshot
        selectionTask = Task.detached(priority: .userInitiated) {
            snapshotter.readSelection()
        }
    }

    /// Called when one chord modifier goes down (the "armed" edge). Warms the
    /// audio engine so a completed chord records from the first syllable.
    /// Gated on the same states startRecording accepts, so a prewarm can't
    /// light the mic indicator while recording would be refused anyway
    /// (model download, permissions error, pipeline in flight).
    func prewarmCapture() {
        switch state.status {
        case .idle, .error:
            capture.prewarm()
        default:
            break
        }
    }

    /// Called when the armed modifier is released without completing the chord.
    func cancelCapturePrewarm() {
        capture.stopPrewarm()
    }

    /// Stop capture, transcribe, run LLM cleanup against the active mode's
    /// prompt, and paste the result into the focused field.
    func finalizeRecording() async {
        // Only valid entry state is `.recording`. A spurious finalize while
        // we're already in `.thinking` (an earlier finalize is mid-flight) or
        // any non-recording state would race with the in-flight pipeline.
        guard case .recording = state.status else { return }
        capture.stop()
        let samples = capture.takeSamples()
        state.status = .thinking
        state.lastRecordingDuration = Double(samples.count) / 16_000.0

        // Silent-capture detector: tap fired (samples non-empty) but no audio
        // signal reached the converter (peak stayed at 0). Almost always means
        // Microphone permission is denied or a muted device was selected.
        if !samples.isEmpty && state.lastPeakLevel == 0 {
            cancelContextTask()
            return setError("No audio captured. Check that Microphone permission is granted and the input device isn't muted.")
        }

        if samples.isEmpty {
            cancelContextTask()
            resetIdle()
            return
        }

        // 1. Transcribe locally.
        let transcript: String
        let transcribeStart = Date()
        do {
            transcript = try await transcriber.transcribe(samples: samples)
        } catch {
            cancelContextTask()
            return setError("Transcription failed. Try again or pick a different model in Settings → General.")
        }
        state.lastTranscribeDuration = Date().timeIntervalSince(transcribeStart)
        state.lastTranscript = transcript

        if transcript.isEmpty {
            // Nothing to clean / paste — quietly idle out.
            cancelContextTask()
            resetIdle()
            return
        }

        // 2. Resolve the active mode by frontmost bundle ID + focused field
        //    snapshot. Falls back to `*` wildcard when nothing matches.
        let bundleID = frontmost.frontmostBundleID()
        let field = fieldInspector.inspect()
        guard let mode = modes.mode(for: bundleID, field: field) else {
            cancelContextTask()
            return setError("No mode for app '\(bundleID ?? "unknown")' and no '*' fallback configured. Open Settings → Modes.")
        }

        // 3. LLM cleanup.
        let context = await contextTask?.value ?? .empty
        contextTask = nil
        let selection = await selectionTask?.value ?? nil
        selectionTask = nil
        // If text was selected when recording started, treat the speech as a
        // command to transform that selection instead of as dictation.
        if let selection, !selection.isEmpty {
            await performTransform(command: transcript, selection: selection, mode: mode, context: context)
            return
        }
        if !context.captureNotes.isEmpty {
            AppLog.context.info("context partial: notes=\(context.captureNotes.joined(separator: ",")) durationMs=\(context.captureDurationMs)")
        }
        let cleaned: String
        let cleanupStart = Date()
        do {
            cleaned = try await llm.cleanup(transcript: transcript, mode: mode, context: context, refinement: nil)
        } catch let e as LLMError {
            transcriptFallback(transcript)
            return setError("\(e.errorDescription ?? "LLM cleanup failed.") Raw transcript copied to the clipboard — paste to recover it.")
        } catch {
            transcriptFallback(transcript)
            return setError("LLM cleanup failed: \(error.localizedDescription) Raw transcript copied to the clipboard — paste to recover it.")
        }
        state.lastCleanupDuration = Date().timeIntervalSince(cleanupStart)
        state.lastCleanedText = cleaned
        historyStore.record(cleanedText: cleaned, mode: mode, context: context)

        // 4. Paste.
        do {
            _ = try await injector.inject(cleaned)
        } catch let e as TextInsertionError {
            return setError(e.errorDescription ?? "Text insertion failed.", permissions: e == .accessibilityNotGranted)
        } catch {
            return setError("Text insertion failed: \(error.localizedDescription)")
        }

        // Offer quick refinements: keep the pill alive for a few seconds.
        startReviewSession(kind: .dictation, transcript: transcript, mode: mode, context: context, insertedText: cleaned)
        resetIdle()
    }

    /// Rewrite the user's selection according to the spoken command, paste it
    /// over the (still-live) selection, and open a transform review session.
    /// Owns its terminal state — callers must not call `resetIdle` afterward.
    private func performTransform(command: String, selection: String, mode: Mode, context: CapturedContext) async {
        let transformed: String
        do {
            transformed = try await llm.transform(instruction: command, selection: selection, mode: mode)
        } catch let e as LLMError {
            return setError("\(e.errorDescription ?? "Transform failed.") Your selection was left unchanged.")
        } catch {
            return setError("Transform failed: \(error.localizedDescription) Your selection was left unchanged.")
        }

        // The transform prompt returns the selection verbatim when the command
        // can't be applied as a rewrite/restructure (e.g. a translate request).
        // Treat that as a no-op rather than re-pasting identical text.
        guard !transformed.isEmpty, transformed != selection else {
            resetIdle()
            showToast("Couldn't apply that")
            return
        }

        historyStore.record(cleanedText: transformed, mode: mode, context: context)

        do {
            // Selection is live, so a paste lands over it — no re-selection needed.
            _ = try await injector.inject(transformed)
        } catch {
            // Any insertion failure: leave the result on the clipboard so ⌘V
            // still replaces the selection.
            transcriptFallback(transformed)
            startReviewSession(kind: .transform, transcript: command, mode: mode, context: context, insertedText: transformed)
            resetIdle()
            showToast("Copied — ⌘V to replace")
            return
        }

        startReviewSession(kind: .transform, transcript: command, mode: mode, context: context, insertedText: transformed)
        resetIdle()
    }

    /// Re-run cleanup on the current review session's transcript with a
    /// refinement directive, then swap the result in place. No-op unless a
    /// session is open and we're idle. On failure the session and the pasted
    /// text are left untouched so the click is retryable.
    func refine(_ directive: RefinementDirective) async {
        guard let session = state.reviewSession, case .idle = state.status else { return }
        pauseReviewExpiry()
        state.status = .thinking

        let cleaned: String
        do {
            switch session.kind {
            case .dictation:
                cleaned = try await llm.cleanup(
                    transcript: session.transcript, mode: session.mode,
                    context: session.context, refinement: directive
                )
            case .transform:
                // Chain on the current text, applying the directive as the
                // instruction — not a re-run of the original spoken command.
                cleaned = try await llm.transform(
                    instruction: directive.promptText,
                    selection: session.insertedText, mode: session.mode
                )
            }
        } catch let e as LLMError {
            state.status = .idle
            showToast(e.errorDescription ?? "Refinement failed.")
            resumeReviewExpiry()
            return
        } catch {
            state.status = .idle
            showToast("Refinement failed: \(error.localizedDescription)")
            resumeReviewExpiry()
            return
        }

        // The session may have been dismissed/scrubbed during the await
        // (MainActor reentrancy). Don't paste or record against a session
        // the user has already dismissed.
        guard state.reviewSession != nil else {
            state.status = .idle
            return
        }

        let outcome = await injector.replace(session.insertedText, with: cleaned)
        state.status = .idle
        historyStore.updateMostRecent(cleanedText: cleaned)
        state.reviewSession?.insertedText = cleaned
        if case .fallbackClipboard = outcome {
            showToast("Copied — ⌘V to replace")
        }
        resumeReviewExpiry()
    }

    /// Dismiss the refinement offer (pill × button).
    func dismissReview() { expireReview() }

    /// Scrub the session and its expiry timer. Idempotent.
    func expireReview() {
        reviewExpiryTask?.cancel()
        reviewExpiryTask = nil
        state.reviewSession = nil
    }

    /// Suspend the expiry countdown (pill hover-in) so a session isn't scrubbed
    /// out from under the pointer.
    func pauseReviewExpiry() {
        reviewExpiryTask?.cancel()
        reviewExpiryTask = nil
    }

    /// Resume the countdown from a full window (pill hover-out, or after a
    /// refine completes). No-op if no session is open.
    func resumeReviewExpiry() {
        guard state.reviewSession != nil else { return }
        state.reviewSession?.expiresAt = now().addingTimeInterval(reviewLingerDuration)
        scheduleReviewExpiry()
    }

    private func startReviewSession(kind: ReviewKind, transcript: String, mode: Mode, context: CapturedContext, insertedText: String) {
        state.reviewSession = ReviewSession(
            kind: kind, transcript: transcript, mode: mode, context: context,
            insertedText: insertedText, expiresAt: now().addingTimeInterval(reviewLingerDuration)
        )
        scheduleReviewExpiry()
    }

    private func clearReviewSession() { expireReview() }

    private func scheduleReviewExpiry() {
        reviewExpiryTask?.cancel()
        let duration = reviewLingerDuration
        // Created in a @MainActor context, so the closure hops back to MainActor.
        reviewExpiryTask = Task { [weak self] in
            try? await Task.sleep(for: .seconds(duration))
            guard !Task.isCancelled else { return }
            self?.expireReview()
        }
    }

    private func showToast(_ message: String) {
        state.toastMessage = message
        Task { [weak self] in
            try? await Task.sleep(for: .seconds(2))
            guard let self else { return }
            if self.state.toastMessage == message { self.state.toastMessage = nil }
        }
    }

    private func cancelContextTask() {
        contextTask?.cancel()
        contextTask = nil
        selectionTask?.cancel()
        selectionTask = nil
    }

    private func resetIdle() {
        state.recordingStartedAt = nil
        state.audioLevel = 0
        state.status = .idle
    }

    private func setError(_ message: String, permissions: Bool = false) {
        state.status = permissions ? .permissionsError(message) : .error(message)
        state.recordingStartedAt = nil
        state.audioLevel = 0
    }
}
