import AppKit
import Foundation

/// Coordinates the hotkey → audio capture → streaming transcription → LLM
/// cleanup → clipboard inject pipeline. Updates AppState along the way.
@MainActor
final class CapturePipeline {

    /// Recordings shorter than this end quietly, as a tap rather than speech.
    static let minimumAudioDuration: TimeInterval = 0.3

    private let state: AppState
    private let capture: AudioCapturing
    private let engines: TranscriptionEngineProviding
    private let llm: LLMServing
    var modes: ModeRouter
    private let frontmost: FrontmostAppProviding
    private let fieldInspector: FocusedFieldInspecting
    private let injector: ClipboardInjecting
    private let historyStore: DictationHistoryStore
    private let contextCapture: ContextCapturing
    private let selectionSnapshot: SelectionSnapshotting
    private let now: @Sendable () -> Date
    let metrics: DictationMetricsStore
    private let llmModelID: @Sendable () -> String
    private let vocabulary: @Sendable () -> [String]
    private let skipShortUtterances: @Sendable () -> Bool

    /// Identifies the current recording. Work resuming after an `await`
    /// compares it with the value it captured and drops its result when a
    /// newer recording has taken over.
    private var generation: UInt64 = 0
    private var live: LiveSession?
    private var startTasks: StartTasks?

    /// Invoked with the raw transcript when LLM cleanup fails, so the user's
    /// words survive a provider outage instead of being discarded. The default
    /// copies to the general pasteboard with the same nspasteboard.org hint
    /// types the injector uses (don't archive in clipboard managers; dictated
    /// speech can be sensitive). Settable so tests observe without touching
    /// NSPasteboard.general.
    var transcriptFallback: (String) -> Void = { transcript in
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(transcript, forType: .string)
        pasteboard.setData(Data(), forType: ClipboardInjector.autoGeneratedType)
        pasteboard.setData(Data(), forType: ClipboardInjector.concealedType)
    }

    init(
        state: AppState,
        capture: AudioCapturing,
        engines: TranscriptionEngineProviding,
        llm: LLMServing,
        modes: ModeRouter,
        frontmost: FrontmostAppProviding,
        fieldInspector: FocusedFieldInspecting,
        injector: ClipboardInjecting,
        historyStore: DictationHistoryStore,
        contextCapture: ContextCapturing,
        selectionSnapshot: SelectionSnapshotting = DefaultSelectionSnapshot(),
        metrics: DictationMetricsStore = DictationMetricsStore(),
        llmModelID: @escaping @Sendable () -> String = { AppSettings().llmModel },
        vocabulary: @escaping @Sendable () -> [String] = { CustomVocabularyStore().load() },
        skipShortUtterances: @escaping @Sendable () -> Bool = { AppSettings().skipShortUtterances },
        now: @escaping @Sendable () -> Date = { Date() }
    ) {
        self.state = state
        self.capture = capture
        self.engines = engines
        self.llm = llm
        self.modes = modes
        self.frontmost = frontmost
        self.fieldInspector = fieldInspector
        self.injector = injector
        self.historyStore = historyStore
        self.contextCapture = contextCapture
        self.selectionSnapshot = selectionSnapshot
        self.metrics = metrics
        self.llmModelID = llmModelID
        self.vocabulary = vocabulary
        self.skipShortUtterances = skipShortUtterances
        self.now = now

        capture.onLevel = { [weak self] level in
            Task { @MainActor in
                self?.state.audioLevel = level
            }
        }
    }

    /// Begin a new recording. Caller must ensure we're not already recording.
    /// `command` reflects whether the command modifier was held at chord
    /// completion; when true this is a transform gesture and the selection is
    /// probed once, here at start. When false (plain dictation) the clipboard
    /// is never touched.
    func startRecording(command: Bool = false) {
        // Reject re-entry while a recording or its post-recording pipeline
        // (transcribe → LLM → paste) is still in flight. `.thinking` covers
        // the entire await chain in finalizeRecording — `state.status` is set
        // to `.thinking` synchronously before any await, so a second call
        // landing on MainActor sees it.
        //
        // Permissions errors are sticky: clearing them on a chord-press
        // would mask a real "tap is uninstalled" condition. Pipeline and
        // modelPrep errors are clearable by the user retrying.
        switch state.status {
        case .recording, .thinking, .downloadingModel, .preparingModel, .permissionsError:
            // A prewarmed engine must not be left running when recording is
            // refused — stopPrewarm is a no-op unless the engine is idling warm.
            capture.stopPrewarm()
            return
        case .idle, .error:
            break
        }
        generation &+= 1
        let live = LiveSession(engine: engines.current)
        capture.onSamples = { [router = live.router] in router.append($0) }
        do {
            try capture.start()
        } catch {
            // A failed start must not strand a prewarmed engine — stopPrewarm
            // is a no-op unless the engine is idling warm. On the warm path,
            // AudioCaptureService.start() can throw AFTER the
            // engine-is-running check (noInputDevice / targetFormatUnavailable
            // / cannotConvertFormat), leaving the engine running with nothing
            // left to stop it.
            capture.stopPrewarm()
            setError("Audio capture failed: \(error.localizedDescription)")
            return
        }
        self.live = live
        state.recordingStartedAt = Date()
        state.audioLevel = 0
        // Scrub the prior dictation's text so it doesn't linger in process
        // memory for the lifetime of the app. Spoken content can include
        // passwords / 2FA codes / private notes; defensible-by-default hygiene.
        state.lastTranscript = nil
        state.lastCleanedText = nil
        state.lastTranscribeDuration = nil
        state.lastCleanupDuration = nil
        state.liveTranscript = nil
        state.retryTranscript = nil
        state.pipelinePhase = nil
        state.isCancellable = true
        state.recordingIsCommand = command
        state.status = .recording
        let generation = self.generation
        live.open(vocabulary: vocabulary) { [weak self] partial in
            guard let self, self.generation == generation else { return }
            self.state.liveTranscript = partial
        }

        let captor = contextCapture
        let frontmost = frontmost
        let fieldInspector = fieldInspector
        let snapshotTask = Task.detached(priority: .userInitiated) {
            let bundleID = frontmost.frontmostBundleID()
            let field = fieldInspector.inspect()
            return StartSnapshot(context: await captor.capture(), bundleID: bundleID, field: field)
        }
        // Selection probe runs ONLY in command mode. In dictation the clipboard
        // is never touched — this is the fix for VS Code's line-copy false
        // positive (empty-selection Cmd+C copies the whole line).
        var selectionTask: Task<String?, Never>?
        if command {
            let snapshotter = selectionSnapshot
            selectionTask = Task.detached(priority: .userInitiated) {
                await snapshotter.readSelection()
            }
        }
        startTasks = StartTasks(snapshot: snapshotTask, selection: selectionTask)
    }

    /// Called when one chord modifier goes down (the "armed" edge). Warms the
    /// audio engine so a completed chord records from the first syllable.
    /// Gated on the same states startRecording accepts, so a prewarm can't
    /// light the mic indicator while recording would be refused anyway
    /// (model download, permissions error, pipeline in flight).
    func prewarmCapture() {
        switch state.status {
        case .idle, .error:
            capture.prewarm()
        default:
            break
        }
    }

    /// Called when the armed modifier is released without completing the chord.
    func cancelCapturePrewarm() {
        capture.stopPrewarm()
    }

    /// The input device went away mid-recording: finish with what was
    /// captured, as if the hotkey had been released. The real release later
    /// finds status past `.recording` and returns immediately.
    func handleCaptureInterrupted() {
        guard case .recording = state.status else { return }
        showToast("Microphone disconnected — stopped recording")
        Task { [weak self] in await self?.finalizeRecording() }
    }

    /// Stop capture, finish the transcription session, run LLM cleanup against
    /// the active mode's prompt, and paste the result into the focused field.
    func finalizeRecording() async {
        // Only valid entry state is `.recording`. A spurious finalize while
        // we're already in `.thinking` (an earlier finalize is mid-flight) or
        // any non-recording state would race with the in-flight pipeline.
        guard case .recording = state.status, let live else { return }
        let generation = self.generation
        let startTasks = self.startTasks
        self.startTasks = nil
        let router = live.router
        let release = ContinuousClock.now
        capture.stop()
        let captureTailMs = Self.milliseconds(release.duration(to: .now))
        state.status = .thinking
        state.pipelinePhase = .transcribing
        state.lastRecordingDuration = router.audioDuration

        if router.sampleCount == 0 || router.audioDuration < Self.minimumAudioDuration {
            await live.cancel()
            guard generation == self.generation else { return }
            startTasks?.cancel()
            resetIdle()
            return
        }

        // Silent-capture detector: audio arrived but every sample was zero.
        // Almost always means Microphone permission is denied or a muted
        // device was selected.
        if router.peak == 0 {
            await live.cancel()
            guard generation == self.generation else { return }
            startTasks?.cancel()
            return setError("No audio captured. Check that Microphone permission is granted and the input device isn't muted.")
        }

        let session: any TranscriptionSession
        do {
            session = try await live.session()
        } catch {
            guard generation == self.generation else { return }
            startTasks?.cancel()
            return setError("Couldn't start \(live.engineName): \(error.localizedDescription)")
        }
        guard generation == self.generation else { return }

        let finishStart = ContinuousClock.now
        let transcript: String
        do {
            transcript = try await session.finish()
        } catch {
            guard generation == self.generation else { return }
            startTasks?.cancel()
            return setError("Transcription failed. Try again or pick a different engine in Settings → General.")
        }
        guard generation == self.generation else { return }
        let transcribeDuration = finishStart.duration(to: .now)
        endLiveSession()
        state.lastTranscribeDuration = Self.seconds(transcribeDuration)
        state.lastTranscript = transcript
        if !state.recordingIsCommand, !transcript.isEmpty {
            state.retryTranscript = transcript
        }

        if transcript.isEmpty {
            // Nothing to clean / paste — quietly idle out.
            startTasks?.cancel()
            resetIdle()
            return
        }
        state.liveTranscript = TranscriptPartial(stable: transcript)

        // Mode resolution uses the frontmost app and focused field as they
        // were at recording start, not wherever focus drifted since.
        let snapshot = await startTasks?.snapshot.value ?? .empty
        guard generation == self.generation else { return }
        guard let mode = modes.mode(for: snapshot.bundleID, field: snapshot.field) else {
            startTasks?.cancel()
            return setError("No mode for app '\(snapshot.bundleID ?? "unknown")' and no '*' fallback configured. Open Settings → Modes.")
        }
        let timing = PipelineTiming(
            release: release,
            captureTailMs: captureTailMs,
            transcribeMs: Self.milliseconds(transcribeDuration),
            engineID: live.engine.metricsID,
            firstPartialMs: live.timeToFirstPartial.map(Self.milliseconds)
        )

        // `recordingIsCommand` was latched at recording start.
        if state.recordingIsCommand {
            let selection = await startTasks?.selection?.value ?? nil
            guard generation == self.generation else { return }
            guard let selection, !selection.isEmpty else {
                // Command gesture but nothing selected: keep the mode boundary
                // crisp — no dictation fallback, no clipboard-probe surprise.
                resetIdle()
                showToast("Select text to transform")
                return
            }
            await performTransform(command: transcript, selection: selection, mode: mode, snapshot: snapshot, timing: timing, generation: generation)
            return
        }
        // Dictation path: no selection probe was spawned, so the clipboard was
        // never touched.
        await performDictation(transcript: transcript, mode: mode, snapshot: snapshot, timing: timing, generation: generation)
    }

    /// Clean up the transcript (or pass it through on the fast path) and
    /// paste it. Owns its terminal state.
    private func performDictation(transcript: String, mode: Mode, snapshot: StartSnapshot, timing: PipelineTiming, generation: UInt64) async {
        let context = snapshot.context
        state.pipelinePhase = .cleaning
        if !context.captureNotes.isEmpty {
            AppLog.context.info("context partial: notes=\(context.captureNotes.joined(separator: ",")) durationMs=\(context.captureDurationMs)")
        }
        let skippedCleanup = skipShortUtterances() && CleanupFastPath.shouldSkip(transcript)
        let cleaned: String
        let cleanupMs: Int
        if skippedCleanup {
            cleaned = transcript
            cleanupMs = 0
            state.lastCleanupDuration = 0
        } else {
            let cleanupStart = ContinuousClock.now
            do {
                let result = try await llm.cleanup(transcript: transcript, mode: mode, context: context)
                guard generation == self.generation else { return }
                cleaned = result
            } catch let e as LLMError {
                guard generation == self.generation else { return }
                transcriptFallback(transcript)
                return setError("\(e.errorDescription ?? "LLM cleanup failed.") Raw transcript copied to the clipboard — paste to recover it.")
            } catch {
                guard generation == self.generation else { return }
                transcriptFallback(transcript)
                return setError("LLM cleanup failed: \(error.localizedDescription) Raw transcript copied to the clipboard — paste to recover it.")
            }
            let cleanupDuration = cleanupStart.duration(to: .now)
            state.lastCleanupDuration = Self.seconds(cleanupDuration)
            cleanupMs = Self.milliseconds(cleanupDuration)
        }
        state.lastCleanedText = cleaned
        historyStore.record(cleanedText: cleaned, rawTranscript: transcript, mode: mode, context: context)
        state.isCancellable = false
        state.pipelinePhase = .inserting

        guard snapshot.field?.isEditable ?? true else {
            transcriptFallback(cleaned)
            recordMetrics(kind: .dictation, timing: timing, cleanupMs: cleanupMs, insertMs: 0, skippedCleanup: skippedCleanup, mode: mode, text: cleaned)
            resetIdle()
            showToast("No text field focused — copied")
            return
        }

        let insertStart = ContinuousClock.now
        do {
            _ = try await injector.inject(cleaned)
        } catch let e as TextInsertionError {
            guard generation == self.generation else { return }
            return setError(e.errorDescription ?? "Text insertion failed.", permissions: e == .accessibilityNotGranted)
        } catch {
            guard generation == self.generation else { return }
            return setError("Text insertion failed: \(error.localizedDescription)")
        }
        guard generation == self.generation else { return }
        recordMetrics(kind: .dictation, timing: timing, cleanupMs: cleanupMs, insertMs: Self.milliseconds(insertStart.duration(to: .now)), skippedCleanup: skippedCleanup, mode: mode, text: cleaned)
        resetIdle()
    }

    /// Rewrite the user's selection according to the spoken command and paste
    /// it over the (still-live) selection.
    /// Owns its terminal state — callers must not call `resetIdle` afterward.
    private func performTransform(command: String, selection: String, mode: Mode, snapshot: StartSnapshot, timing: PipelineTiming, generation: UInt64) async {
        // The AX reader returns the FULL live selection (no truncation), and
        // `injector.inject` below pastes back over that same full live
        // selection. If we let an over-long selection through, the LLM would
        // only see/rewrite the first `selectionMax` characters while the
        // paste still overwrites the entire selection — silently dropping
        // the untransformed tail. Refuse instead of desyncing read/write.
        guard selection.count <= DefaultSelectionSnapshot.selectionMax else {
            resetIdle()
            showToast("Selection too long to transform")
            return
        }

        state.pipelinePhase = .cleaning
        let transformed: String
        let transformStart = ContinuousClock.now
        do {
            let result = try await llm.transform(instruction: command, selection: selection, mode: mode)
            guard generation == self.generation else { return }
            transformed = result
        } catch let e as LLMError {
            guard generation == self.generation else { return }
            return setError("\(e.errorDescription ?? "Transform failed.") Your selection was left unchanged.")
        } catch {
            guard generation == self.generation else { return }
            return setError("Transform failed: \(error.localizedDescription) Your selection was left unchanged.")
        }
        let cleanupMs = Self.milliseconds(transformStart.duration(to: .now))

        // Focus/selection may have moved during the LLM await. If the live
        // selection no longer matches what we transformed, don't overwrite
        // the wrong target — leave the result on the clipboard for a manual
        // paste instead.
        let liveSelection = await selectionSnapshot.readSelection()
        guard generation == self.generation else { return }
        guard liveSelection == selection else {
            transcriptFallback(transformed)
            resetIdle()
            showToast("Copied — ⌘V to replace")
            return
        }

        // The transform prompt returns the selection verbatim when the command
        // can't be applied as a rewrite/restructure (e.g. a translate request).
        // Treat that as a no-op rather than re-pasting identical text.
        guard !transformed.isEmpty, transformed != selection else {
            resetIdle()
            showToast("Couldn't apply that")
            return
        }

        historyStore.record(cleanedText: transformed, rawTranscript: command, mode: mode, context: snapshot.context)
        state.isCancellable = false
        state.pipelinePhase = .inserting

        guard snapshot.field?.isEditable ?? true else {
            transcriptFallback(transformed)
            recordMetrics(kind: .command, timing: timing, cleanupMs: cleanupMs, insertMs: 0, mode: mode, text: transformed)
            resetIdle()
            showToast("Copied — ⌘V to replace")
            return
        }

        let insertStart = ContinuousClock.now
        do {
            // Selection is live, so a paste lands over it — no re-selection needed.
            _ = try await injector.inject(transformed)
        } catch {
            guard generation == self.generation else { return }
            // Any insertion failure: leave the result on the clipboard so ⌘V
            // still replaces the selection.
            transcriptFallback(transformed)
            recordMetrics(kind: .command, timing: timing, cleanupMs: cleanupMs, insertMs: 0, mode: mode, text: transformed)
            resetIdle()
            showToast("Copied — ⌘V to replace")
            return
        }
        guard generation == self.generation else { return }
        recordMetrics(kind: .command, timing: timing, cleanupMs: cleanupMs, insertMs: Self.milliseconds(insertStart.duration(to: .now)), mode: mode, text: transformed)
        resetIdle()
    }

    // MARK: - Snapshot and metrics

    /// Work started alongside a recording. Finalize takes ownership before its
    /// first await, so it can never cancel or clear a later recording's tasks.
    private struct StartTasks {
        let snapshot: Task<StartSnapshot, Never>
        let selection: Task<String?, Never>?

        func cancel() {
            snapshot.cancel()
            selection?.cancel()
        }
    }

    private struct StartSnapshot: Sendable {
        let context: CapturedContext
        let bundleID: String?
        let field: FocusedField?

        static let empty = StartSnapshot(context: .empty, bundleID: nil, field: nil)
    }

    private struct PipelineTiming {
        let release: ContinuousClock.Instant
        let captureTailMs: Int
        let transcribeMs: Int
        let engineID: String
        let firstPartialMs: Int?
    }

    private func recordMetrics(kind: DictationMetrics.Kind, timing: PipelineTiming, cleanupMs: Int, insertMs: Int, skippedCleanup: Bool = false, mode: Mode, text: String) {
        metrics.record(DictationMetrics(
            timestamp: now(),
            kind: kind,
            audioDuration: state.lastRecordingDuration ?? 0,
            captureTailMs: timing.captureTailMs,
            transcribeMs: timing.transcribeMs,
            cleanupMs: cleanupMs,
            insertMs: insertMs,
            totalMs: Self.milliseconds(timing.release.duration(to: .now)),
            engineID: timing.engineID,
            modelID: mode.model ?? llmModelID(),
            wordCount: text.split(whereSeparator: \.isWhitespace).count,
            firstPartialMs: timing.firstPartialMs,
            skippedCleanup: skippedCleanup
        ))
    }

    /// Truncates, so stage times never sum past the total measured around them.
    private static func milliseconds(_ duration: Duration) -> Int {
        Int(duration / .milliseconds(1))
    }

    private static func seconds(_ duration: Duration) -> TimeInterval {
        duration / .seconds(1)
    }

    // MARK: - Terminal states

    private func showToast(_ message: String) {
        state.toastMessage = message
        Task { [weak self] in
            try? await Task.sleep(for: .seconds(2))
            guard let self else { return }
            if self.state.toastMessage == message { self.state.toastMessage = nil }
        }
    }

    private func resetIdle() {
        clearRecordingState()
        state.status = .idle
    }

    private func setError(_ message: String, permissions: Bool = false) {
        state.status = permissions ? .permissionsError(message) : .error(message)
        clearRecordingState()
    }

    /// Stops feeding and observing the current session, which must already be
    /// finished or cancelled, and lets go of its router.
    private func endLiveSession() {
        live?.close()
        live = nil
        capture.onSamples = nil
    }

    /// Shared by idle and error. `retryTranscript` survives both.
    private func clearRecordingState() {
        endLiveSession()
        state.recordingStartedAt = nil
        state.audioLevel = 0
        state.liveTranscript = nil
        state.pipelinePhase = nil
        state.isCancellable = false
    }
}
